#########################################################
#              UHC HOST -  Version 1.3                  #
#                 Author : B. Goodes                    #
#########################################################

World:
  default-world: 'world' #The name of the server's default world
  world-name : 'uhc'
  seed: 0   # 0 --> random
  dimension: "NORMAL" #NORMAL | NETHER | END
  type: "NORMAL" #NORMAL | LARGE_BIOMES | AMPLIFIED | FLAT | VERSION_1_1 | CUSTOMIZED
  generate-structures: true
  
Lobby:
  location: 
    world-name: 'world'
    x: 0
    y: 200
    z: 0
  cage:
     generate: true
     size: 25
     height: 4
  player-damage: false
  
Game:
   create-default-game: true #Allow to create a game automatically at server launch.
   default-game-mode: "CLASSIC" #CLASSIC | DEVIL_WATCHES | TAUPE_GUN
   auto-host: true #The first player (with uhc.host perm) to join the game becomes host.
   
ServerManager: 
  log-game-broadcast: true #Allows to authorize sending game's messages in console.
  generate-worlds: true #Allow to generate worlds automatically at server launch.
  delete-worlds: true #Allow to delete uhc's worlds automatically at server close/reload. /!\ Don't work with the server's default world
  server-restart: true #Allow to restart the server after game

Permissions:
  remove-op: false #Allows to remove automatically the op tag of players
  set-op-to-host: false #Allows to give automatically the rank "Staff" to host
  
Scoreboard:
  ip:
    show-ip: true
    ip: play.serveur.fr
    ip-color:
      text-color: AQUA
    fade:
      ip-fade: true
      ip-fade-cooldown: 50
      ip-fade-unit: 80 #Milliseconds
      ip-fade-color: 
        point: DARK_PURPLE
        fade: LIGHT_PURPLE
    
    
  
  