name: UHC-HOST
version: 1.4
author: B. Goodes
main: fr.aiidor.uhc.UHC
commands:
  host:
    description: Commands for UHC organizers.
  h:
    description: Commands for UHC organizers.
  scenarios:
    description: Commands to see UHC scenarios.
  dw:
    description: DW-UHC related commands.
  taupe:
    description: Taupe-Gun related commands. 
  t:
    description: Taupe-Gun related commands. 
  msg:
   description: Command to send private messages.